import "bootstrap/dist/css/bootstrap.css";
import '@/styles/globals.css'
import '@/styles/responsive.css'
import '@/styles/fonts.css'

import { Fragment } from 'react';
import Head from 'next/head';

import DefaultLayout from "../components/layout/DefaultLayout";


import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';

import Store from '@/contexts/Store'

export default function App({ Component, pageProps }) {
  return (
    <Fragment>
      <Head>
        <title>Massage MNL</title>
        <meta name="description" content="Generated by create next app" />
        {/* <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0,user-scalable=0"/>
	      <meta name='robots' content='index, follow, max-image-preview:large, max-snippet:-1, max-video-preview:-1' />
      </Head>
      <link rel="icon" href="../assets/image/favicon.png" />

      <DefaultLayout>
        <Store>
          <Component {...pageProps} />
        </Store>
			</DefaultLayout>

      <Header />

      {/* <main>
      <MassageModal />
        <Component {...pageProps}  />
      </main>

      <Footer /> */}

    </Fragment>
  );
}
